### ISSUE TITLE
Does not work with HTTPS protocol

### ISSUE THREAD

**Issue by tomassliz** [netguru/ResponseDetective#1]
I tried to send request with URL [https://httpbin.org/xml](https://httpbin.org/xml) and it seems that communication is broken. No response is delivered until timeout.

I have only this one interceptor:

``` swift
InterceptingProtocol.registerResponseInterceptor(XMLInterceptor())
```

**Comment by akashivskyy** [comment]
Does this happen in playgrounds or in app targets as well?

**Comment by tomassliz** [comment]
I tried this only in app target - new clean iOS project.

**Comment by akashivskyy** [comment]
@tomassliz Please check if the latest commit fixed your issue. You may install latest HEAD version by using `"master"` in your `Cartfile`:

``` none
github "netguru/ResponseDetective" "master"
```

**Comment by tomassliz** [comment]
I can't install latest HEAD version. This is output of `carthage update` command:

```
*** Cloning ResponseDetective
*** Checking out ResponseDetective at "99a7428b07a7ffbd54d5613c87f27dd7f0538807"
*** xcodebuild output can be found in /var/folders/3s/5fmt6_0d6zx7m316ynk2_4cr0000gn/T/carthage-xcodebuild.iRaoun.log
*** Building scheme "ResponseDetective (iOS)" in ResponseDetective.xcodeproj
** BUILD FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
A shell task failed with exit code 65
```

I tried to create new project or clean Carthage cache. So it's maybe problem with your framework settings.

**Anyway, if I clone your project and build the latest HEAD version manually everything is ok and the original issue is fixed.**

**Comment by akashivskyy** [comment]
Installation fails because of code signing issues, please make sure that you have a valid provisioning profile for any framework to be built. :smiley:

**Comment by tomassliz** [comment]
I don't think that code signing is the problem. Problem is that you have private dependencies and that's why Carthage can't build it. Look at this:

```
~/Desktop/Detective $ carthage update --platform ios --verbose
*** Fetching ResponseDetective
*** Checking out ResponseDetective at "cc54353fa3994436192298f199bab9f9242350e9"
*** Building scheme "ResponseDetective (iOS)" in ResponseDetective.xcodeproj
Build settings from command line:
    SDKROOT = iphonesimulator8.4

=== BUILD TARGET ResponseDetective (iOS) OF PROJECT ResponseDetective WITH CONFIGURATION Release ===

Check dependencies
The file “Release.xcconfig” couldn’t be opened because there is no such file. (/Users/deny/Desktop/Detective/Carthage/Checkouts/ResponseDetective/Carthage/Checkouts/xcconfigs/Base/Configurations/Release.xcconfig)
The file “iOS-Framework.xcconfig” couldn’t be opened because there is no such file. (/Users/deny/Desktop/Detective/Carthage/Checkouts/ResponseDetective/Carthage/Checkouts/xcconfigs/iOS/iOS-Framework.xcconfig)
Build setting PRODUCT_NAME undefined

** BUILD FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
A shell task failed with exit code 65
```

**Comment by akashivskyy** [comment]
Looks like I have to include `Carthage/Checkouts` as submodules (Carthage/Carthage#278)... But that's another issue, so I'm closing this for now and will release a pre-built 0.2 version for now. :)

**Comment by tomassliz** [comment]
Thank you, I♥️ this project idea.

**Comment by akashivskyy** [comment]
@tomassliz FYI, 0.2 is now live. :smiley:
