### ISSUE TITLE
Error while building the project

### ISSUE THREAD

**Issue by khurramengr** [netguru/ResponseDetective#19]
ld: /Users/user_name/Library/Developer/Xcode/DerivedData/Project_Name-gblnftdcyqwoicfexphoypuxrrfl/Build/Products/Debug-iphonesimulator/ResponseDetective/ResponseDetective.framework/ResponseDetective compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**XCode 8 Beta 3**

I've enabled the "Use Legacy Swift Version" to 'yes' but still getting this error.

**Comment by akashivskyy** [comment]
Hi! Swift 3 migration is tracked by #13, and a pull request #18 is already in progress. Will keep you updated!

**Comment by khurramengr** [comment]
@akashivskyy if it supports Swift 2.3 then it should work with "Use Legacy Swift Version" set to 'yes'

**Comment by akashivskyy** [comment]
It is set to "yes" in [ResponseDetective-Common.xcconfig](https://github.com/netguru/ResponseDetective/blob/develop/Configuration/ResponseDetective-Common.xcconfig#L42). 😉 

It looks like you're trying to `import` a pre-built Swift 2.3 version in Swift 3. If you're using Carthage, please use `--no-use-binaries` flag until a Swift 3 version is released.

**Comment by akashivskyy** [comment]
@khurramengr: Just FYI, [ResponseDetective 1.0 has been released](https://github.com/netguru/ResponseDetective/releases/tag/1.0). 😉
