### ISSUE TITLE
Does not work with skipped certificate validation

### ISSUE THREAD

**Issue by tomassliz** [netguru/ResponseDetective#2]
I have to use server with invalid SSL certificate for development. So I set up Alamofire manager to skipping SSL verification with this code (applicable for `NSURLSession` too):

```
manager.delegate.sessionDidReceiveChallenge = { session, challenge in
    if challenge.protectionSpace.authenticationMethod == "NSURLAuthenticationMethodServerTrust" {
        return (.UseCredential, NSURLCredential(forTrust: challenge.protectionSpace.serverTrust))
    }

    return (.PerformDefaultHandling, nil)
}
```

When I try to use your library with this setup, communication is interrupted and this line is printed out:

```
NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9814)
```

So is possible to use your library with skipped certificate verification?

**Comment by akashivskyy** [comment]
Not yet. There were [plans to implement this](https://github.com/netguru/ResponseDetective/blob/519cb973a3a008ea329a0d448bd95a677dd1ad0a/ResponseDetective/Source%20Files/InterceptingProtocol.swift#L177-L180), but they didn't make it to the 0.1 release.

We'll focus on that in the next iteration (and you can contribute as well, if you'd like). :wink:

**Comment by tomassliz** [comment]
I would like to contribute but I don't know how to implement this. Alamofire solved this with own block property. But when you do the same, where should be then the right place for setting up this block? In your library or in Alamofire? I don't know.

**Comment by akashivskyy** [comment]
I think the best way would be to use the underlying implementation that exists in `NSURLSession`'s delegate (so there's no need to duplicate your code).

But there's no easy way of accessing it, because `NSURLProtocol` only receives `NSURLRequest`, without the information of which session is responsible for it. :confused:
