### ISSUE TITLE
 a shell task failed with exit code 65

### ISSUE THREAD

**Issue by SandeepAggarwal** [netguru/ResponseDetective#22]
While installing this as a framework using Carthage I am getting following error:
> a shell task failed with exit code 65

You may find a similar issue which occurred with Charts library here:
https://github.com/danielgindi/Charts/issues/1476

**Comment by akashivskyy** [comment]
Hi! When installing dependencies with Carthage, it gives you a URL to `xcodebuild` log. Can you paste its contents here?

**Comment by SandeepAggarwal** [comment]
/usr/bin/xcrun xcodebuild -project "/pathToMyProject/Carthage/Checkouts/ResponseDetective/ResponseDetective.xcodeproj" -scheme iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos10.1

Build Preparation
Build task concurrency set to 4 via user default IDEBuildOperationMaxNumberOfConcurrentCompileTasks

=== CLEAN TARGET ResponseDetective (iOS) OF PROJECT ResponseDetective WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

Build Preparation
Build task concurrency set to 4 via user default IDEBuildOperationMaxNumberOfConcurrentCompileTasks

=== BUILD TARGET ResponseDetective (iOS) OF PROJECT ResponseDetective WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by SandeepAggarwal** [comment]
Cartfile:

github "https://github.com/netguru/ResponseDetective.git" "feature/swift-3-dev"

**Comment by akashivskyy** [comment]
Are you using Xcode 8.3 Beta?

**Comment by SandeepAggarwal** [comment]
No Xcode 8.1

**Comment by akashivskyy** [comment]
This is an Xcode bug which [has been fixed in Xcode 8.2.1](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html#//apple_ref/doc/uid/TP40001051-CH1-SW157):

> Fixed an issue that could cause building a project to fail with the error message “"Use Legacy Swift Language Version" (SWIFT_VERSION) is required to be configured correctly for targets which use Swift” when using a supported version of Swift. (29667880)

Please update Xcode to 8.2.1 and check whether the error still occurs.

**Comment by SandeepAggarwal** [comment]
Thanks, I will  update the Xcode and will let you know the status of this issue.

**Comment by akashivskyy** [comment]
Please note that `feature/swift-3-dev` branch has been deleted and you now need to target `develop` (or wait for version 1.0). 😉

**Comment by SandeepAggarwal** [comment]
Thanks @akashivskyy  you saved my next 30 minutes :)

**Comment by SandeepAggarwal** [comment]
It is working fine in Xcode 8.2.1

**Comment by akashivskyy** [comment]
✨
