### ISSUE TITLE
Project broken

### ISSUE THREAD

**Issue by laindow** [netguru/ResponseDetective#25]
I add your library by use CocoaPods.
It have a lot of errors and Xcode 8 cannot compile it.
Looks like it done on Swift 2 not on Swift 3 like it pretend to be.

**Comment by akashivskyy** [comment]
[RespondeDetective 0.5](https://github.com/netguru/ResponseDetective/releases/tag/0.5), which is the latest version, is written in Swift 2. If you want to use Swift 3 version, please explicitly use bleeding-edge `develop` branch or wait for 1.0 release which is coming very, very soon.

**Comment by akashivskyy** [comment]
@laindow: Just FYI, [ResponseDetective 1.0 has been released](https://github.com/netguru/ResponseDetective/releases/tag/1.0). 😉
