### ISSUE TITLE
Can't import ResponseDetective

### ISSUE THREAD

**Issue by yousefhamza** [netguru/ResponseDetective#27]
I tried playing around with your library, I installed it with cocoapods I couldn't import it, tried your playground got `No such module... ` error, tried it on another machine same thing.
my xcode version 8.0, second machine xcode version 8.2

**Comment by akashivskyy** [comment]
Which ResponseDetective version are you using?

**Comment by yousefhamza** [comment]
I'm using the `develop` branch for Swift 3

**Comment by akashivskyy** [comment]
The `develop` branch, as the name suggests, is not stable. I'll let you know when stable 1.0 is released.

**Comment by yousefhamza** [comment]
But it's the only version working with xcode 8, What branch/version shall I use to use it with xcode 8?

**Comment by akashivskyy** [comment]
@yousefhamza: [ResponseDetective 1.0 has been released](https://github.com/netguru/ResponseDetective/releases/tag/1.0). 😉
