### ISSUE TITLE
Installation with cocoapods is failing

### ISSUE THREAD

**Issue by combinatorial** [netguru/ResponseDetective#3]
cocoapods: 0.38.0 & 0.38.2

Analyzing dependencies
[!] Unable to satisfy the following requirements:
- `ResponseDetective` required by `Podfile`

**Comment by combinatorial** [comment]
I realized I didn't have the right min SDK version. I fixed that, now I get the error...

[!] Pods written in Swift can only be integrated as frameworks; this feature is still in beta. Add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: ResponseDetective

So I added `use_frameworks!` and it worked

**Comment by akashivskyy** [comment]
Glad you've found the source of the issue. I will add the information about `use_frameworks!` to README. :smiley:
