### ISSUE TITLE
Request Body is always <none>  in Content-Type: multipart/form-data;

### ISSUE THREAD

**Issue by adamhongmy** [netguru/ResponseDetective#38]
├─ Headers
 │ Content-Type: multipart/form-data; boundary=----------V2ymHFg03ehbqgZCaKO6jy
 │ User-Agent: apps;iOS;10.3;1.0;75F64A34-78C9-4D27-8C5D-6FDA9FCEE1D6;Apple;Simulator
 │ Content-Length: 2157
 ├─ Body
 │ <none>

**Comment by akashivskyy** [comment]
(Sorry for a late response, I totally missed the notification on this issue).

ResponseDetective doesn't support `multipart/form-data` requests. They are very complex and may contain multiple segments with multiple content-types which makes them particularly hard to implement correctly.

That being said, the support for `multipart/form-data` will be a point of focus in the next major release, that is 2.0.

**Comment by adamhongmy** [comment]
Oh I see. Well I hope you able to implement it in version 2. :D cheers

**Comment by akashivskyy** [comment]
This will be tracked by #39 – you can subscribe for updates under that issue. 😉
