### ISSUE TITLE
Using from Obj-C

### ISSUE THREAD

**Issue by runeb** [netguru/ResponseDetective#4]
The generated ResponseDetective-Swift.h header file only exposes the class `InterceptingProtocol` and its methods `+unregisterAllRequestInterceptors`, `+unregisterAllResponseInterceptors`, `+unregisterAllErrorInterceptors` in addition to the `NSURLProtocol` and delegate methods.

There is therefore no way to register any interceptors, nor get at their classes.

Edit: This is from the 0.2 downloaded framework

**Comment by akashivskyy** [comment]
ResponseDetective is not yet compatible with Objective-C.

Having said that, this is a major area of focus in the next interation and I can promise that Objective-C support is soming soon. :wink:

**Comment by akashivskyy** [comment]
This has been included in the upcoming 0.4 release.
