### ISSUE TITLE
Unsupported on Carthage 0.26.2

### ISSUE THREAD

**Issue by Maciej-Matuszewski** [netguru/ResponseDetective#46]
On Carthage 0.26.2 on bootstrap there is exit code 66. In logs there is information`xcodebuild: error: Scheme iOS is not currently configured for the archive action.`

**Comment by akashivskyy** [comment]
Carthage 0.26 now uses `archive` when building against device SDK, so that apps don't get rejected for using LLVM instrumentation (code coverage) in frameworks.

I will release a new version of ResponseDetective which supports archiving (I have no idea why it doesn't support it already).
