### ISSUE TITLE
Update Cocoapods to 1.2.3

### ISSUE THREAD

**Issue by jessemx109** [netguru/ResponseDetective#52]
Please update the Podspec to include the new 1.2.3 so the library can be used on xcode 9.3

**Comment by akashivskyy** [comment]
Oh, my bad. I can't release 1.2.3 to CocoaPods without doing a force push, so I will release 1.2.4.

**Comment by bpolat** [comment]
Can you please update pod for Xcode 9.3?

**Comment by akashivskyy** [comment]
Released as 1.2.4 and pushed to CocoaPods trunk. Sorry for 1.2.3 not being there. 😔

Please open a new issue if there are any further problems.
