### ISSUE TITLE
Carthage *** Skipped installing ResponseDetective.framework binary due to the error:

### ISSUE THREAD

**Issue by adamhongmy** [netguru/ResponseDetective#53]
<img width="1085" alt="screen shot 2018-04-03 at 11 40 53 am" src="https://user-images.githubusercontent.com/11060748/38228042-e612a788-3733-11e8-9ba5-d45d4dc86981.png">

> *** Skipped installing ResponseDetective.framework binary due to the error:
> 	"Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."

I googled this similar issue seems other libraries such as [this](https://github.com/realm/realm-cocoa/issues/5709) did complain about this too and it is related to Xcode 9.3 and Swift 4.1.

**Comment by akashivskyy** [comment]
The latest stable release of ResponseDetective includes a pre-compiled binary for Swift 4.0.3. This is not going to change until the next version.

What you see is not an installation error because in your case, Carthage will compile the library manually anyway.

**Comment by adamhongmy** [comment]
Alright, what should I do to resolve this then?

**Comment by akashivskyy** [comment]
To resolve what exactly? 😉 This is **not** an error, it's just a message from Carthage that it will compile the library because the pre-compiled binary was made with an earlier Swift version.

**Comment by adamhongmy** [comment]
:anguished:
