### ISSUE TITLE
Crash on iOS 13.4 (EXC_BAD_ACCESS)

### ISSUE THREAD

**Issue by skvasov** [netguru/ResponseDetective#58]
**What happened:**
The library has started crashing after updating to iOS 13.4 both simulator and device.

com.apple.CFNetwork.CustomProtocols (119): EXC_BAD_ACCESS (code=EXC_i386_GPFLT)

**Where:**
URLProtocol.swift line 43

**Environment:**
MacOS 10.15.4
Xcode 11.4
iOS 13.4
ResponseDetective 1.3.0
CocoaPods 1.9.1

<img width="1440" alt="Screen Shot 2020-03-25 at 18 36 10" src="https://user-images.githubusercontent.com/9040925/77662921-7f989780-6f8d-11ea-9335-753f8127bf60.png">

**Comment by akashivskyy** [comment]
Thanks for reporting! I opened a PR with the fix and will release 1.4.0 ASAP.

**Comment by akashivskyy** [comment]
Released. It should be available on CocoaPods once #60 is done. Cheers!
