### ISSUE TITLE
Push version 1.4.0 to CocoaPods

### ISSUE THREAD

**Issue by akashivskyy** [netguru/ResponseDetective#60]
I just released version 1.4.0, it needs to be pushed to CocoaPods trunk. Seems I have lost my powers to do this myself. 😉

This only needs a `pod trunk push` from `master`. Everything else is ready. Alternatively, you can add me to the ResponseDetective's trunk as collaborator (you should have my email).

**Comment by Siemian** [comment]
Thank you for your contribution.
```
 🎉  Congrats

 🚀  ResponseDetective (1.4.0) successfully published
 📅  March 27th, 08:49
 🌎  https://cocoapods.org/pods/ResponseDetective
 👍  Tell your friends!
```
