### ISSUE TITLE
Runtime crash

### ISSUE THREAD

**Issue by laindow** [netguru/ResponseDetective#61]
Hello guys,

  After I updated Xcode to 11.4 I got this exception on start.

    	/// A unique identifier of the request. Currently its address.
	private lazy var requestIdentifier: String = String(describing: Unmanaged<AnyObject>.passUnretained(self.internalTask.originalRequest! as AnyObject).toOpaque())

  com.apple.CFNetwork.CustomProtocols (12): EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

![Screen Shot 2020-04-05 at 23 03 29](https://user-images.githubusercontent.com/1131118/78499097-002b7500-7792-11ea-95e5-e6af80136f5b.png)

Best regards,
Konstantin

**Comment by akashivskyy** [comment]
Hi Konstantin! This has been fixed in #59. Please upgrade ResponseDetective to version 1.4.0 and the problem should go away.

**Comment by laindow** [comment]
Hello guys,

  Actually I have it in version 1.4 so it still here.
  My solution replace this line in URLProtocol.swift

	private lazy var requestIdentifier: String = String(describing: Unmanaged<AnyObject>.passUnretained(self.internalTask.originalRequest! as AnyObject).toOpaque())

  To this one
	private lazy var requestIdentifier: String = UUID().uuidString


Best regards,
Konstantin.
