### ISSUE TITLE
Swift 2 Support

### ISSUE THREAD

**Issue by rajohns08** [netguru/ResponseDetective#9]
Could you create a Swift 2 branch with instructions on how to install that branch via cocoa pods like alamofire has?

**Comment by akashivskyy** [comment]
We want to deliver the best debugging functionality for production projects. Since most of them use Objective-C and/or Swift 1.2, we want to focus on those languages.

Nevertheless, Swift 2.0 support is certainly coming soon, and will probably be released by the end of September.

**Comment by davejlong** [comment]
Any update on this? With Xcode 7 forcing developers to upgrade apps to Swift 2, ResponseDetective just became utterly useless.

**Comment by akashivskyy** [comment]
@davejlong That's our top priority right now, expect an update in a couple of days. :wink:

**Comment by davejlong** [comment]
Thanks. Was a little nervous seeing no commits on the project in a month.

**Comment by akashivskyy** [comment]
Sorry, had some high-priority issues in other projects (and a vacation). The development on ResponseDetective will return at full speed in October!

**Comment by akashivskyy** [comment]
That went quicker than expected.

**Comment by akashivskyy** [comment]
ResponseDetective 0.3 is now available via Carthage and CocoaPods.

**Comment by davejlong** [comment]
Dang. That's a hell of a responsive OSS owner. Thanks @akashivskyy

**Comment by davejlong** [comment]
One minor change to README in PR #11
